<?php


namespace SIGA\Forms;


use SIGA\TableView\TableViewForm;

class ProfileForm extends TableViewForm
{

    public function buildForm()
    {

        $this
            ->add('name', 'text',[
                'label_show' => false,
            ])
            ->add('email', 'email',[
                'label_show' => false,
            ])
            ->add('phone', 'text',[
                'label_show' => false,
            ])
            ->add('document', 'text',[
                'label_show' => false,
            ])
            ->add('birthday', 'date',[
                'label_show' => false,
            ])
            ->add('gender', 'choice',[
                'choices' => ['male' => 'Male', 'femele' => 'Femele'],
                'label_show' => false,
                'selected' => "male",
                'expanded' => true
            ])
            ->add('description', 'textarea',[
                'label_show' => false,
            ])
            ->add('publish', 'checkbox',[
                'label_show' => false,
            ]);
        parent::buildForm(); // TODO: Change the autogenerated stub
    }
}
