<?php


namespace SIGA\Forms;


use SIGA\TableView\TableViewForm;

class ProfileForm extends TableViewForm
{

    public function buildForm()
    {
        $this->getModel();
        $this
            ->add('id', 'hidden',[
                'label_show' => false,
            ])
            ->add('name', 'text',[
                'label_show' => false,
            ])
            ->add('email', 'email',[
                'label_show' => false,
            ])
            ->add('phone', 'text',[
                'label_show' => false,
            ])
            ->add('document', 'text',[
                'label_show' => false,
            ])
            ->add('birthday', 'date',[
                'label_show' => false,
            ])
            ->add('gender', 'choice',[
                'choices' => ['male' => 'Male', 'femele' => 'Femele'],
                'label_show' => false,
                'selected' => "male",
                'expanded' => true
            ])
            ->add('description', 'textarea',[
                'label_show' => false,
            ])
            ->add('status', 'choice',[
                'choices' => ['published' => 'Publiched', 'draft' => 'Draft'],
                'label_show' => false,
                'selected' => "published",
                'expanded' => true
            ]);
        parent::buildForm(); // TODO: Change the autogenerated stub
    }
}
